language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '10'
  - '8'
  - '6'
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm test
  - codecov
after_success:
  - if [ "$TRAVIS_BRANCH" == "feature/saucelab" ]; then
      npx travis-deploy-once;
      npm run build;
      npx semantic-release;
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
